<!DOCTYPE html>

<html lang="en">

<head>
	<title>Sky Riders balloon Pilots</title>
	<meta content="balloon flight,balloon ride,hot air balloon,balloon PA, hot air balloon rides,hot air balloon flights,ballooning,balloon,Philadelphia,Trappe,Sky Riders,air balloon,balloon montgomery county,skyriders" name="Keywords">
	<meta name="viewport" content="width=device-width, initial-scale=1">
	<meta http-equiv="Content-Type" content="text/html; charset=unicode">
	<meta name="description" content="Sky Riders hot air balloon team pilots, balloon crew">
	<meta name="image" content="http://www.skyridersballoon.com/images/sun.jpg">
	<!-- Schema.org for Google -->
	<meta itemprop="name" content="Sky Riders Balloon Tours">
	<meta itemprop="description" content="Sky Riders hot air balloon team pilots, balloon crew">
	<meta itemprop="image" content="http://www.skyridersballoon.com/images/sun.jpg">
	<!-- Open Graph general (Facebook, Pinterest & Google+) -->
	<meta name="og:title" content="Sky Riders Balloon Tours">
	<meta name="og:description" content="Sky Riders hot air balloon team pilots, balloon crew">
	<meta name="og:image" content="http://www.skyridersballoon.com/images/sun.jpg">
	<meta name="og:url" content="http://www.skyridersballoon.com">
	<meta name="og:site_name" content="Sky Riders Balloon Tours">
	<meta name="og:type" content="website">
	<link rel="profile" href="http://microformats.org/profile/hcard">
	<link href="css/styles.css" type="text/css" rel="stylesheet">
	<!--[if IE 6]>
		<link rel="STYLESHEET" type="text/css" href="css/styles_ie6.css">
	<![endif]-->
	<script src="js/jquery-1.4.2.min.js" type="text/javascript"></script>
	<script src="js/jquery.colorbox-min.js"></script>

	<script>
		$(document).ready(function() {

			$("#galtrigger").click(function() {
				$("a[rel='galleryimg']").colorbox({
					transition: "fade",
					slideshow: true,
					open: true
				});

			});
		});
	</script>
</head>
<!-- JSON-LD markup generated by Google Structured Data Markup Helper. -->
<script type="application/ld+json">
	{
		"@context": "http://schema.org",
		"@type": "LocalBusiness",
		"name": "Sky Riders Balloon Team",
		"image": "http://www.skyridersballoon.com/images/gallery/789_8963.JPG",
		"telephone": "484-744-3161",
		"email": "pilot@skyridersballoon.com",
		"address": {
			"@type": "PostalAddress",
			"addressLocality": "Montgomery County",
			"addressRegion": "PA",
			"addressCountry": "USA"
		}
	}
</script>

<body>

	<div id="rightcolumn" class="right"></div>

	<div id="leftcolumn" class="left"></div>
	<div id="maincontainer">
		<?php include_once('nav.php') ?>
		<div id="logo">

			<img src="images/logo.jpg" width="253" height="137" alt="Sky Rider Balloon Tours" border="0" align="left" />
			<div id="callout">Balloon Team</div>
		</div>
		<div id="contentarea">

			<div class="story">
				<h1 style="font-size:1.25em;">DIRECTIONS TO THE TRAPPE TAVERN</h1>
				<h2><span class="adr"><span class="street-address">416 Main Street</span>, <span class="locality">Trappe</span> <span class="region">PA</span> <span class="postal-code">19426</span></span></h2>
				<div class="contentbox">

					<div class="storybox">
						<p><span class="yellow">From 422 (Pottstown or King of Prussia)</span><br />


							Take 422 to the Collegeville/Phoenixville exit.<br />
							At the ramp, head toward Collegeville<br />

							After 2.3 miles (gas station on your right) make a left onMain Street toward Trappe<br />

							Shortly after crossing route 113, <strong>the Trappe Tavern</strong> will on your left
						</p>

						<p><span class="yellow">From Philadelphia:</span><br />

							Take 76 to King of Prussia then follow directions above from 422</p>

						<p><span class="yellow">From East or West:</span><br />

							Take route 202 or 276 to King of Prussia then follow directions from 422</p>


					</div>


				</div>
			</div>

			<div class="story">
				<h1>WHERE TO STAY?</h1>
				<h2>Do you need a romantic place to stay before or <br />
					after your flight?</h2>
				<div class="contentbox">

					<div class="storybox">
						<div class="picbox  left">
							<img src="images/Shearerelegance.jpg" width="220" height="146" alt="Shearer Elegance bed and breakfast" border="0" />
						</div>
						<p>Shearer Elegance bed and breakfast 1154 Main St, Linfield, PA - only a few miles away Built in 1897, a beautiful 22-room 10,000-square-foot Victorian mansion situated on more than 2 acres of
							beautifully manicured gardens and lawn.</p>

						<p><span class="yellow">Reservations: 610-495-7429 or <a href="http://www.shearerelegance.com/" target="_blank">web site</a></span></p>
						<p>Click <a href="http://maps.google.com/maps?f=d&source=s_d&saddr=416+main+street,+Trappe,+pa&daddr=1154+main+street,+linfield,+pa&hl=en&mra=ls&sll=40.203526,-75.484314&sspn=0.313083,0.550003&ie=UTF8&ll=40.15736,-75.49427&spn=0.156649,0.275002&z=12" target="_blank">HERE</a> to see a google map of the area including Trappe (A) and Linfield (B)
							You can also get directions from your address. </p>

					</div>
				</div>
			</div>




		</div>
		<?php include_once('footer.php') ?>

	</div>
	<?php include 'gallery.html'; ?>
	<script type="text/javascript">
		var _gaq = _gaq || [];
		_gaq.push(['_setAccount', 'UA-19260420-1']);
		_gaq.push(['_trackPageview']);

		(function() {
			var ga = document.createElement('script');
			ga.type = 'text/javascript';
			ga.async = true;
			ga.src = ('https:' == document.location.protocol ? 'https://ssl' : 'http://www') + '.google-analytics.com/ga.js';
			var s = document.getElementsByTagName('script')[0];
			s.parentNode.insertBefore(ga, s);
		})();
	</script>
</body>

</html>